### PR TITLE
Hotfix 1.0.1

### PR DESCRIPTION
**Pull request by thaije**
### Related Issue
#122 

### Those responsible
@jwaa, @thaije 

### Description
See issue #122 

### Release notes
- Fixed a bug that discluded all teamplates from the MATRX visualizer folder for the PyPi distribution of MATRX.

### CODE REVIEW

**Comment by thaije** [comment]
@jwaa would you be so kind as to review this humble request?

**Comment by thaije** [comment]
@jwaa By the way, I redeployed this branch as 1.0.1 instead of 1.0.1a0, as the latter is a pre-release and is not used by default when installing matrx using pip.

**Comment by matrx-software** [comment]
@thaije But ofcourse, I would love to indulge you with this humble request! :)

I added the alpha stage for us to try out the deployment of the new distribution without messing with anyone who happens to be installing MATRX at that time.

Will you tag it in master and make a new release here in GitHub? In our How To Contribute guide is a link to a blog that tells you how to make tags and what formate we follow. You can take a look at out v1.0.0 release here in Github and mimick that for the v1.0.1 release.

**Comment by thaije** [comment]
@jwaa I deployed the V1.0.1. release here on github. I added the tag to the master branch: 
`git tag v1.0.1 -a`
`git push --tags`

Followed by adding a new release, by Drafting a new release [here](https://github.com/matrx-software/matrx/releases) and connecting to the v1.0.1 tag. 

Is that the way to go? Also, did you add the release notes yourself to release V1.0.0, or was that automatically done using the RELEASE_NOTES.txt which is mentioned in the Contribution guide, but I can't find anywhere? 
 
Also, according to the guide linked in the [contribution guide](https://nvie.com/posts/a-successful-git-branching-model/), the release_v1.0 branch should now be closed / removed right?

**Comment by jwaa** [comment]
@thaije You did great! 

I changed the RELEASE_NOTES.txt to a HISTORY.txt that contains all release notes. I will change it on the contribution guide. 

You are right, I removed the release and hotfix branch.

**Pull request merged**
