### PR TITLE
Closes #150 - implemented subtile functionality

### LINKED ISSUE #150: Place objects in subtiles in visualization
**Is your feature request related to a problem? Please describe.**
This feature request came from the researchers working on the RVO Human-Agent Teaming at TNO, in specific the Co-active teaming team. 

The request boils down for a simple method for an agent to be able to see all objects within a tile at once. The specific the team above were trying to solve was having an agent step into a room (a single tile), and see all the objects in that room at once. 

**Describe the solution you would like**
They requested for it to be possible to place multiple objects in one tile, using a subtile feature. When placing an object, in addition to the specific location of an object, more specific placing can then be achieved with the subtile functionality. You pass in how many subtiles that tile is subdivided [rows, columns] for placing that object, and the specific placing in that subtile framework of that object [row, column]. 

**Describe alternatives you have considered**
This functionality can also be achieved with the default MATRX functionality. For instance, create a room object with walls. Let the agent filter out everything from its observed state that is not within that room. The advantage of this solution is that you can create large rooms of variable size and shape. The downside is that it requires a bit more programming. 

**Additional context**
This had already been implemented in an earlier version of MATRX for the Co-active teaming project, and now has been ported to the new MATRX version. As such, it has already been implemented in the Co-active teaming usecase, but the question is whether it should be incorporated in the base MATRX visualizer. A downside of not doing so is that the co-active teaming usecase does not work with the default visualizer.

### PR DESCRIPTION
**Pull request by thaije**
### Related Issue
#150

### Those responsible
@thaije 

### Description
Added feature for placing objects in the visualizer in subtiles. 

### Release notes
Added feature for placing objects in the visualizer in subtiles.

### CODE REVIEW

**Comment by thaije** [comment]
@jwaa Could you check this merge? See feature #150, for co-active teaming we used a subtile feature, which I had to port to the new MATRX version for that project. However, I don't know if we want to include this in our default MATRX visualizer. This is I think part of our discussion on whether we should provide multiple methods for achieving the same thing or not, as you can achieve issue #150 also without this feature as described under alternatives in issue #150. It is already implemented and tested though, so the extra effort is not the issue :)

**Comment by thaije** [comment]
This feature might be incompatible, or atleast display improperly, in combination with feature #98

**Comment by jwaa** [comment]
> This feature might be incompatible, or atleast display improperly, in combination with feature #98

So to be clear; this combination is not tested yet?
If it does not combine, I would say that the sub-tile functionality percedes the 'thinking icon'. But that is just my guess that people use sub-tiles probably for a better reason than turning the thinking icon on.

**Comment by jwaa** [comment]
I will try and review it tomorrow!

**Comment by thaije** [comment]
Hey @jwaa, the reason I think these two features might be fully compatible is that the loading icon normally displays in the top right, which might be where an object is fully placed with the subtile functionality. 
Also, what was our plan for the subtile functionality? I remember we had a discussion on whether we wanted this feature in MATRX or not, but I don't remember the conclusion.

**Comment by jwaa** [comment]
@thaije, I think we decided to add it. Since it was implemented anyway and it could have its benefits. However, this was before it conflicted with another MATRX' feature. But still I think it is worth it to add. We just have to document it well.

**Pull request merged**
